server:
  addr: ":8082"
token:
  issuer: "Local Registry Auth Service"
  expiration: 900
  certificate: "./root.crt"
  key: "./private_key.pem"
acl:
- match: {account: "admin"}
    actions: ["*"]
    comment: "Admin has full access to everything."