version: 0.1
log:
  level: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
http:
  addr: :5000
  net: tcp
  secret: asecretforlocaldevelopment
  debug:
    addr: :5001
auth:
  token:
    realm: http://192.168.21.175:8082/v1/registry/callback/auth
    service: "Local Registry Server"
    issuer: "Local Registry Auth Service"
    rootcertbundle: /etc/registry/root.crt
notifications:
  endpoints:
    - name: alistener
      disabled: false
      url: http://192.168.21.175:8082/v1/registry/callback/event
      headers:
        Authorization:
        - just4fun
      timeout: 500ms
      threshold: 5
      backoff: 3s
      ignoredmediatypes:
        - application/octet-stream