apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: boxlinker
spec:
  rules:
  - host: es.boxlinker.com
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch
          servicePort: 9200
  tls:
  - hosts:
    - es.boxlinker.com
    secretName: lb-cert
