FROM alpine:latest
RUN apk update
RUN apk add ca-certificates
RUN apk add tzdata

RUN mkdir /app
RUN mkdir /ssl
COPY ./cmd/registry/image-api /app/image-api
COPY ./cmd/registry/ssl /ssl
RUN chmod +x /app/image-api

WORKDIR /app

CMD /app/image-api --config-file /app/config/auth_config.yml

