apiVersion: v1
kind: Service
metadata:
  name: index
  namespace: boxlinker
  labels:
    app: index
spec:
  ports:
  - port: 5000
    name: index
  - port: 5001
    name: auth
---
apiVersion: v1
kind: Endpoints
metadata:
  name: index
  namespace: boxlinker
subsets:
- ports:
  - port: 5000
    name: index
  - port: 5001
    name: auth
  addresses:
  - ip: "192.168.99.100"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/client-max-body-size: "0"
  name: index
  namespace: boxlinker
spec:
  rules:
  - host: index.dev.boxlinker.com
    http:
      paths:
      - backend:
          serviceName: index
          servicePort: 5000
        path: /
      - backend:
          serviceName: index
          servicePort: 5001
        path: /auth
