apiVersion: v1
kind: Service
metadata:
  name: web-console
  namespace: boxlinker
  labels:
    app: web-console
spec:
  selector:
    app: web-console
  ports:
  - port: 3000
    name: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-console
  namespace: boxlinker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-console
    spec:
      imagePullSecrets:
      - name: registry-key
      containers:
      - env:
        - name: NODE_ENV
          value: production
        image: index.boxlinker.com/boxlinker/web-console:v1
        imagePullPolicy: Always
        name: web-console
        ports:
        - containerPort: 3000
          name: pro
          protocol: TCP
      nodeSelector:
        role: system
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-console
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - console.boxlinker.com
    secretName: lb-cert
  rules:
  - host: console.boxlinker.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web-console
          servicePort: 3000
