apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: cabernety
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "test"
    spec:
      containers:
      - name: test
        imagePullPolicy: Always
        image: registry.cn-beijing.aliyuncs.com/cabernety/nginx:alpine
        ports:
        - containerPort: 80