apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  namespace: boxlinker
spec:
  rules:
  - host: api.boxlinker.com
    http:
      paths:
      - path: /v1/registry
        backend:
          serviceName: email
          servicePort: 8080
  tls:
  - hosts:
    - api.boxlinker.com
    secretName: lb-cert
