apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
  namespace: boxlinker
  labels:
    name: rabbitmq
spec:
  replicas: 1
  selector:
    name: rabbitmq
  template:
    metadata:
      labels:
        name: rabbitmq
        logs: boxlinker-rabbitmq
    spec:
      nodeSelector:
        role: user
      imagePullSecrets:
      - name: registry-key
      containers:
      - name: rabbitmq
        imagePullPolicy: Always
        #image: registry.cn-beijing.aliyuncs.com/cabernety/rabbitmq:latest
        image: index.boxlinker.com/library/rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: tcp
        - containerPort: 15672
          name: mgr
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: boxlinker
  labels:
    name: rabbitmq
spec:
  selector:
    name: rabbitmq
  sessionAffinity: ClientIP
  ports:
  - name: rabbitmq
    protocol: TCP
    port: 5672
  - name: mgr
    protocol: TCP
    port: 15672
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq-mgr
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - rabbitmq-mgr.boxlinker.com
    secretName: lb-cert
  rules:
  - host: rabbitmq-mgr.boxlinker.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rabbitmq
          servicePort: 15672