apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes
  namespace: boxlinker
  annotations:
    #ingress.kubernetes.io/ssl-passthrough: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: arand0mdevmaster1ngressh0st.boxlinker.com
    http:
      paths:
      - path: /
        backend:
          serviceName: k8s
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s
  namespace: boxlinker
  labels:
    app: k8s
spec:
  ports:
  - port: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: k8s
  namespace: boxlinker
subsets:
- addresses:
  - ip: 172.20.1.26
  ports:
  - name: k8s
    port: 8080
    protocol: TCP
