kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-gitlab-0
  namespace: boxlinker
  annotations:
    volume.beta.kubernetes.io/storage-class: rbd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
