apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: boxlinker
spec:
  rules:
  - host: git.boxlinker.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
  tls:
  - hosts:
    - git.boxlinker.com
    secretName: lb-cert
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: boxlinker
  labels:
    app: "gitlab"
spec:
  ports:
  - port: 80
  selector:
    app: "gitlab"
