apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-rc
  namespace: boxlinker
  labels:
    app: nginx-ingress
spec:
  replicas: 1
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      nodeSelector:
        role: loadbalancer
      containers:
      - image: registry.cn-beijing.aliyuncs.com/cabernety/nginx-ingress:0.9.0
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        # Uncomment the lines below to enable extensive logging and/or customization of
        # NGINX configuration with configmaps
        args:
        - -v=3
        - -nginx-configmaps=boxlinker/lb-config
